[build]
  command = "npm run build"
  publish = ".next"

# Build configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = false

[build.processing.html]
  pretty_urls = true

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Functions
[functions]
  directory = "netlify/functions"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
