[build]
  command = "npm run build"
  publish = ".next"

# Standard Next.js deployment
[build.environment]
  NODE_VERSION = "18"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Next.js plugin for better detection
[[plugins]]
  package = "@netlify/plugin-nextjs"
